import {
  IRRIGATION_HANDBOOK_SOURCE_ID,
  IRRIGATION_HANDBOOK_TITLE,
} from "@/lib/knowledge-base/domains/irrigation-manifest";

import { assignGlobalIrrIds, draftNode, rewireDependsOnToIrrIds } from "./assign-irr-ids";
import { assertValidBookMap } from "./validate-book-map";
import type { BookMapNodeDraft } from "./assign-irr-ids";
import type { BookMap, BookMapChapter } from "./types";

const n = draftNode;

function section(
  id: string,
  order: number,
  titleFr: string,
  titleEn: string,
  role: "learning_path" | "reference",
  purpose: string,
  pageStart: number | undefined,
  nodes: BookMapNodeDraft[],
  pageEnd?: number,
) {
  return {
    id,
    order,
    titleFr,
    titleEn,
    role,
    pageStart,
    pageEnd,
    purpose,
    nodes,
  };
}

function chapter(
  def: Omit<BookMapChapter, "sections"> & { sections: ReturnType<typeof section>[] },
): BookMapChapter {
  return def as BookMapChapter;
}

const RAW_IRRIGATION_HANDBOOK_MAP = assignGlobalIrrIds({
  sourceId: IRRIGATION_HANDBOOK_SOURCE_ID,
  titleFr: "Maîtriser l'irrigation : Guide stratégique du cultivateur moderne",
  titleEn: IRRIGATION_HANDBOOK_TITLE,
  author: "Julien Ricco · Botafarm",
  totalPages: 113,
  documentLanguage: "fr",
  referencePrefix: "IRR",
  sourceDocumentHint:
    "Botafarm Strategie d'irrigationFR.pdf — structure only; no document stored in repo",
  chapters: [
    chapter({
      id: "ch-01-introduction",
      number: 1,
      order: 1,
      titleFr: "Introduction à l'irrigation stratégique",
      titleEn: "Introduction to strategic irrigation",
      role: "learning_path",
      pageStart: 4,
      pageEnd: 5,
      purpose:
        "Frame irrigation as crop steering: frequency, volume, and timing drive vegetative vs generative balance.",
      sections: [
        section(
          "ch-01-s1-strategic-framing",
          1,
          "Irrigation comme pilotage",
          "Irrigation as crop control",
          "learning_path",
          "Establish why irrigation is a control lever, not a routine.",
          4,
          [
            n({
              kind: "concept",
              slug: "strategic-irrigation",
              label: "Strategic irrigation",
              summary:
                "Frequency, volume, and timing of each irrigation shift plant physiology and final crop structure.",
              targetConceptSlug: "irrigation-strategy",
              brainCategory: "Irrigation",
              relatedMetrics: ["irrigation_count", "irrigation_volume_per_event"],
              phases: ["Vegetative", "Flower"],
            }),
            n({
              kind: "concept",
              slug: "substrate-as-dashboard",
              label: "Substrate as dashboard",
              summary:
                "Saturation, dryback speed, and in/out EC reveal root metabolism — the grower reads the pot, not only the canopy.",
              dependsOn: ["strategic-irrigation"],
              brainCategory: "Irrigation",
              relatedMetrics: ["dryback_percent", "ec_in", "ec_runoff"],
              phases: ["All"],
            }),
            n({
              kind: "concept",
              slug: "crop-steering-intro",
              label: "Crop steering introduction",
              summary:
                "Irrigation steers hormonal balance between vegetative and generative development when paired with environment.",
              dependsOn: ["strategic-irrigation"],
              targetConceptSlug: "vegetative-steering",
              brainCategory: "Crop Steering",
              phases: ["Vegetative", "Flower"],
            }),
            n({
              kind: "warning",
              slug: "poor-irrigation-blocks-flower",
              label: "Poor calibration blocks flowering",
              summary:
                "Mis-timed or excessive irrigation can stall flowering or cause uncontrolled stretch.",
              dependsOn: ["crop-steering-intro"],
              phases: ["Flower", "Pre-Flower"],
            }),
            n({
              kind: "warning",
              slug: "late-irrigation-session-risk",
              label: "Late irrigation risk",
              summary:
                "A single poorly timed late pulse can undermine an entire photoperiod dryback strategy.",
              dependsOn: ["substrate-as-dashboard"],
              phases: ["Flower", "Vegetative"],
            }),
          ],
        ),
      ],
    }),
    chapter({
      id: "ch-02-substrate",
      number: 2,
      order: 2,
      titleFr: "Comprendre la structure du substrat et les dynamiques d'eau",
      titleEn: "Substrate structure and water dynamics",
      role: "learning_path",
      pageStart: 6,
      pageEnd: 8,
      purpose:
        "Explain retention, drainage, and aeration differences before any pulse schedule.",
      dependsOnChapterIds: ["ch-01-introduction"],
      sections: [
        section(
          "ch-02-s1-substrate-fundamentals",
          1,
          "Dynamique de l'eau dans le substrat",
          "Water dynamics in substrate",
          "learning_path",
          "Substrate choice determines retention, oxygen, and steering sensitivity.",
          6,
          [
            n({
              kind: "concept",
              slug: "substrate-water-dynamics",
              label: "Substrate water dynamics",
              summary:
                "Each substrate retains and drains differently; irrigation must match that physical behavior.",
              dependsOn: ["substrate-as-dashboard"],
              brainCategory: "Irrigation",
              phases: ["All"],
            }),
            n({
              kind: "concept",
              slug: "field-capacity-substrate",
              label: "Field capacity in substrate",
              summary:
                "Target saturation band where roots have water, air, and nutrient mobility without waterlogging.",
              dependsOn: ["substrate-water-dynamics"],
              targetConceptSlug: "field-capacity",
              brainCategory: "Irrigation",
              relatedMetrics: ["dryback_percent"],
              phases: ["Vegetative", "Flower"],
            }),
            n({
              kind: "concept",
              slug: "coco-vs-rockwool",
              label: "Coco vs rockwool behavior",
              summary:
                "Coco saturates and dries quickly with forgiving steering; rockwool demands frequent small pulses and tight control.",
              dependsOn: ["substrate-water-dynamics"],
              phases: ["All"],
            }),
            n({
              kind: "rule",
              slug: "each-drop-has-intent",
              label: "Each irrigation has intent",
              summary:
                "Every pulse affects oxygen, nutrient mobility, osmotic balance, and hormonal response — not filler water.",
              dependsOn: ["substrate-water-dynamics"],
              brainCategory: "Irrigation",
            }),
            n({
              kind: "concept",
              slug: "root-zone-oxygen-balance",
              label: "Root zone oxygen balance",
              summary:
                "Too much water suffocates roots; too little creates hydraulic stress — balance drives absorption.",
              dependsOn: ["field-capacity-substrate"],
              targetConceptSlug: "root-zone-oxygenation",
              brainCategory: "Irrigation",
              relatedMetrics: ["dryback_percent", "runoff_percent"],
              phases: ["Vegetative", "Flower"],
            }),
            n({
              kind: "warning",
              slug: "surface-dry-misread",
              label: "Surface dry misread",
              summary:
                "Dry surface with wet core is common — weigh pots or use probes instead of touching tops only.",
              dependsOn: ["substrate-water-dynamics"],
              phases: ["All"],
            }),
          ],
        ),
      ],
    }),
    chapter({
      id: "ch-03-dryback",
      number: 3,
      order: 3,
      titleFr: "Le dryback : fondations du pilotage des cultures (crop steering)",
      titleEn: "Dryback foundations of crop steering",
      role: "learning_path",
      pageStart: 9,
      pageEnd: 10,
      purpose: "Define dryback as an active steering tool between irrigations, not idle time.",
      dependsOnChapterIds: ["ch-02-substrate"],
      sections: [
        section(
          "ch-03-s1-dryback-definition",
          1,
          "Qu'est-ce que le dryback",
          "What dryback is",
          "learning_path",
          "Moisture loss between pulses sends a metabolic signal to the plant.",
          9,
          [
            n({
              kind: "concept",
              slug: "dryback-definition",
              label: "Dryback definition",
              summary:
                "Dryback is substrate moisture loss between irrigations — measured by weight, runoff, or capacitive probes.",
              dependsOn: ["field-capacity-substrate"],
              targetConceptSlug: "dryback",
              brainCategory: "Irrigation",
              relatedMetrics: ["dryback_percent"],
              phases: ["Vegetative", "Flower"],
            }),
            n({
              kind: "metric",
              slug: "dryback-percent-metric",
              label: "Dryback percent",
              summary: "Primary steering metric — percent substrate weight or VWC lost between pulses.",
              dependsOn: ["dryback-definition"],
              relatedMetrics: ["dryback_percent"],
              phases: ["Vegetative", "Flower"],
            }),
          ],
        ),
        section(
          "ch-03-s2-dryback-by-phase",
          2,
          "Dryback léger vs agressif",
          "Light vs aggressive dryback",
          "learning_path",
          "Phase determines dryback intensity and hormonal outcome.",
          9,
          [
            n({
              kind: "concept",
              slug: "light-dryback-vegetative",
              label: "Light dryback in vegetative",
              summary:
                "Vegetative steering uses ~5–10% dryback between pulses to keep roots active without harsh stress.",
              dependsOn: ["dryback-definition"],
              targetConceptSlug: "vegetative-steering",
              brainCategory: "Crop Steering",
              relatedMetrics: ["dryback_percent"],
              phases: ["Vegetative"],
            }),
            n({
              kind: "concept",
              slug: "aggressive-dryback-flower",
              label: "Aggressive dryback in flower",
              summary:
                "Generative steering uses ~15–30%+ dryback to reduce turgidity and prioritize reproductive metabolism.",
              dependsOn: ["dryback-definition"],
              targetConceptSlug: "generative-steering",
              brainCategory: "Crop Steering",
              relatedMetrics: ["dryback_percent"],
              phases: ["Flower"],
            }),
            n({
              kind: "concept",
              slug: "overnight-dryback-window",
              label: "Overnight dryback window",
              summary:
                "Dryback begins after the last daily pulse and continues through lights-off; morning substrate should be appropriately dry for generative steering.",
              dependsOn: ["aggressive-dryback-flower"],
              targetConceptSlug: "overnight-dryback",
              brainCategory: "Irrigation",
              relatedMetrics: ["dryback_percent"],
              phases: ["Flower"],
            }),
            n({
              kind: "warning",
              slug: "excessive-dryback-salt-spike",
              label: "Excessive dryback salt spike",
              summary:
                "Prolonged dryness concentrates salts, spikes EC, and shifts from steering to survival stress.",
              dependsOn: ["aggressive-dryback-flower"],
              relatedMetrics: ["ec_runoff", "dryback_percent"],
              phases: ["Flower"],
            }),
          ],
          10,
        ),
      ],
    }),
    chapter({
      id: "ch-04-vegetative",
      number: 4,
      order: 4,
      titleFr: "Irrigation en croissance végétative",
      titleEn: "Irrigation in vegetative growth",
      role: "learning_path",
      pageStart: 11,
      pageEnd: 14,
      purpose: "Support structure and root mass with moderate pulses — avoid over-watering early cycle.",
      dependsOnChapterIds: ["ch-03-dryback"],
      sections: [
        section(
          "ch-04-s1-veg-principles",
          1,
          "Principes végétatifs",
          "Vegetative steering principles",
          "learning_path",
          "Larger pulses, fewer events, moderate dryback, early-day timing.",
          11,
          [
            n({
              kind: "rule",
              slug: "veg-pulse-volume-range",
              label: "Vegetative pulse volume",
              summary: "Typical vegetative pulse ~5–8% of pot volume per event.",
              dependsOn: ["light-dryback-vegetative"],
              relatedMetrics: ["irrigation_volume_per_event"],
              phases: ["Vegetative"],
            }),
            n({
              kind: "rule",
              slug: "veg-pulse-frequency",
              label: "Vegetative pulse frequency",
              summary: "Often 1–2 pulses per day (sometimes 3 in very dry environments).",
              dependsOn: ["veg-pulse-volume-range"],
              relatedMetrics: ["irrigation_count"],
              phases: ["Vegetative"],
            }),
            n({
              kind: "rule",
              slug: "veg-moderate-dryback",
              label: "Vegetative moderate dryback",
              summary: "Maintain ~5–10% dryback between irrigations during vegetative build.",
              dependsOn: ["light-dryback-vegetative"],
              relatedMetrics: ["dryback_percent"],
              phases: ["Vegetative"],
            }),
            n({
              kind: "rule",
              slug: "veg-first-shot-after-lights",
              label: "First shot after lights-on",
              summary: "First vegetative pulse ideally 30–60 minutes after lights-on (H+1), not at flip.",
              dependsOn: ["veg-pulse-frequency"],
              targetConceptSlug: "first-shot-timing",
              relatedMetrics: ["irrigation_count"],
              phases: ["Vegetative"],
            }),
          ],
        ),
        section(
          "ch-04-s2-veg-practice",
          2,
          "Pratique et exemple 11 L",
          "Practice and 11 L example",
          "learning_path",
          "Translate principles into a concrete daily pattern and EC/runoff guardrails.",
          12,
          [
            n({
              kind: "concept",
              slug: "veg-example-schedule",
              label: "Vegetative example schedule",
              summary:
                "Example: ~500 mL first pulse near H+1 in 11 L (~4.5%), optional small second pulse if VPD is high; no night irrigation.",
              dependsOn: ["veg-first-shot-after-lights"],
              phases: ["Vegetative"],
            }),
            n({
              kind: "rule",
              slug: "veg-ec-range",
              label: "Vegetative EC range",
              summary: "Target roughly 1.0–2.0 mS/cm in — adjust by strain response and leaf health.",
              dependsOn: ["veg-example-schedule"],
              relatedMetrics: ["ec_in"],
              brainCategory: "Nutrition",
              phases: ["Vegetative"],
            }),
            n({
              kind: "rule",
              slug: "veg-runoff-requirement",
              label: "Vegetative runoff requirement",
              summary: "In inert media (coco), aim ~10–15% runoff per irrigation to prevent salt buildup.",
              dependsOn: ["veg-example-schedule"],
              targetConceptSlug: "runoff-percent",
              relatedMetrics: ["runoff_percent", "ec_runoff"],
              phases: ["Vegetative"],
            }),
            n({
              kind: "warning",
              slug: "veg-over-irrigation-stagnation",
              label: "Vegetative over-irrigation",
              summary:
                "Excess water in vegetative phase stagnates roots and blocks uptake — common beginner mistake.",
              dependsOn: ["veg-example-schedule"],
              phases: ["Vegetative"],
            }),
          ],
          13,
        ),
        section(
          "ch-04-s3-veg-to-flower",
          3,
          "Transition vers le génératif",
          "Transition to generative",
          "learning_path",
          "Move to generative irrigation only when structure and roots are ready.",
          13,
          [
            n({
              kind: "concept",
              slug: "veg-to-generative-readiness",
              label: "Readiness for generative steering",
              summary:
                "Shift when canopy structure, root fill, and stretch signals justify generative stress — not before the base is built.",
              dependsOn: ["veg-runoff-requirement"],
              targetConceptSlug: "generative-steering",
              brainCategory: "Crop Steering",
              phases: ["Pre-Flower", "Flower"],
            }),
          ],
          14,
        ),
      ],
    }),
    chapter({
      id: "ch-05-flower",
      number: 5,
      order: 5,
      titleFr: "Irrigation en floraison (générative)",
      titleEn: "Irrigation in generative flowering",
      role: "learning_path",
      pageStart: 15,
      pageEnd: 18,
      purpose: "Compress internodes and drive floral development via frequency, dryback, and environment synergy.",
      dependsOnChapterIds: ["ch-04-vegetative"],
      sections: [
        section(
          "ch-05-s1-frequency-volume",
          1,
          "Fréquence élevée — volume réduit",
          "High frequency, reduced volume",
          "learning_path",
          "Many small pulses replace large vegetative shots during generative steering.",
          15,
          [
            n({
              kind: "rule",
              slug: "flower-high-frequency-pulses",
              label: "High-frequency small pulses",
              summary: "Generative phase uses more daily pulses at smaller volumes versus vegetative.",
              dependsOn: ["veg-to-generative-readiness"],
              relatedMetrics: ["irrigation_count", "irrigation_volume_per_event"],
              phases: ["Flower"],
            }),
          ],
        ),
        section(
          "ch-05-s2-dryback-stress",
          2,
          "Dryback accentué",
          "Accentuated dryback",
          "learning_path",
          "Stronger between-pulse drying drives generative hormonal prioritization.",
          15,
          [
            n({
              kind: "concept",
              slug: "flower-accentuated-dryback",
              label: "Accentuated generative dryback",
              summary: "Increase dryback severity to reduce vegetative turgidity and focus on flower production.",
              dependsOn: ["aggressive-dryback-flower", "flower-high-frequency-pulses"],
              relatedMetrics: ["dryback_percent"],
              phases: ["Flower"],
            }),
          ],
        ),
        section(
          "ch-05-s3-diurnal-irrigation",
          3,
          "Irrigation strictement diurne",
          "Strictly diurnal irrigation",
          "learning_path",
          "All irrigation occurs in the lit window; nights are dryback-only.",
          16,
          [
            n({
              kind: "rule",
              slug: "flower-diurnal-only",
              label: "Diurnal irrigation only",
              summary: "No night pulses — dryback extends through lights-off for root respiration and pathogen control.",
              dependsOn: ["flower-accentuated-dryback"],
              phases: ["Flower"],
            }),
          ],
        ),
        section(
          "ch-05-s4-ec-control",
          4,
          "EC élevé mais maîtrisé",
          "Elevated but controlled EC",
          "learning_path",
          "Higher in EC supports generative metabolism when runoff stays balanced.",
          16,
          [
            n({
              kind: "rule",
              slug: "flower-elevated-ec",
              label: "Elevated generative EC",
              summary: "Run higher in EC during active generative steering while monitoring out vs in.",
              dependsOn: ["flower-diurnal-only"],
              relatedMetrics: ["ec_in", "ec_runoff"],
              brainCategory: "Nutrition",
              phases: ["Flower"],
            }),
          ],
        ),
        section(
          "ch-05-s5-vpd-light",
          5,
          "VPD et lumière en synergie",
          "VPD and light synergy",
          "learning_path",
          "Generative irrigation assumes coordinated VPD and light intensity.",
          17,
          [
            n({
              kind: "concept",
              slug: "flower-vpd-light-synergy",
              label: "VPD and light synergy",
              summary: "Dryback speed depends on VPD — generative steering pairs irrigation timing with environment targets.",
              dependsOn: ["flower-elevated-ec"],
              targetConceptSlug: "vpd",
              brainCategory: "Environment",
              relatedMetrics: ["vpd", "temperature", "humidity"],
              phases: ["Flower"],
            }),
          ],
          18,
        ),
      ],
    }),
    chapter({
      id: "ch-06-timing",
      number: 6,
      order: 6,
      titleFr: "Taille, fréquence et timing des irrigations",
      titleEn: "Shot size, frequency, and timing",
      role: "learning_path",
      pageStart: 20,
      pageEnd: 23,
      purpose: "Operationalize pulse volume, daily count, and photoperiod placement (P1/P2/P3).",
      dependsOnChapterIds: ["ch-05-flower"],
      sections: [
        section(
          "ch-06-s1-shot-size",
          1,
          "La taille des pulses",
          "Shot size",
          "learning_path",
          "Volume per pulse must hydrate the full root zone without channeling.",
          20,
          [
            n({
              kind: "concept",
              slug: "pulse-size-root-zone",
              label: "Pulse size for full root zone",
              summary: "Each pulse should wet the entire substrate profile — undersized shots leave dry cores.",
              dependsOn: ["flower-high-frequency-pulses"],
              relatedMetrics: ["irrigation_volume_per_event"],
              phases: ["Vegetative", "Flower"],
            }),
          ],
        ),
        section(
          "ch-06-s2-frequency",
          2,
          "La fréquence",
          "Frequency",
          "learning_path",
          "Daily pulse count follows phase goals and environmental demand.",
          21,
          [
            n({
              kind: "rule",
              slug: "frequency-by-phase",
              label: "Frequency by phase",
              summary: "Vegetative: fewer larger events; generative: more fractional pulses through the lit period.",
              dependsOn: ["pulse-size-root-zone"],
              relatedMetrics: ["irrigation_count"],
              phases: ["Vegetative", "Flower"],
            }),
          ],
        ),
        section(
          "ch-06-s3-timing-p-phases",
          3,
          "Le timing — P1, P2, P3",
          "Timing — P1, P2, P3",
          "learning_path",
          "Photoperiod irrigation windows: post-wake ramp (P1), maintenance (P2), overnight dryback (P3).",
          22,
          [
            n({
              kind: "concept",
              slug: "p1-first-shots",
              label: "P1 first shots",
              summary:
                "P1: small spaced pulses after stomata open (H+1 onward) to reach field capacity without channeling.",
              dependsOn: ["frequency-by-phase", "veg-first-shot-after-lights"],
              targetConceptSlug: "p1-irrigation",
              relatedMetrics: ["irrigation_count", "irrigation_volume_per_event"],
              phases: ["Vegetative", "Flower"],
            }),
            n({
              kind: "concept",
              slug: "p2-maintenance-shots",
              label: "P2 maintenance shots",
              summary:
                "P2: optional maintenance pulses if VWC drops too fast during the lit period — more in vegetative, reduced in generative.",
              dependsOn: ["p1-first-shots"],
              targetConceptSlug: "p2-irrigation",
              relatedMetrics: ["irrigation_count", "dryback_percent"],
              phases: ["Vegetative", "Flower"],
            }),
            n({
              kind: "concept",
              slug: "p3-overnight-dryback",
              label: "P3 overnight dryback",
              summary: "P3: no irrigation after lights-off — controlled dryback until next P1.",
              dependsOn: ["p2-maintenance-shots"],
              targetConceptSlug: "p3-irrigation",
              relatedMetrics: ["dryback_percent"],
              phases: ["Vegetative", "Flower"],
            }),
            n({
              kind: "rule",
              slug: "lit-window-h1-to-h6",
              label: "Lit window H+1 to H+6",
              summary: "Irrigate between ~H+1 and H+6; never at lights-on; never during the dark period.",
              dependsOn: ["p1-first-shots"],
              targetConceptSlug: "last-shot-timing",
              phases: ["Vegetative", "Flower"],
            }),
            n({
              kind: "warning",
              slug: "post-h6-irrigation-pathogens",
              label: "Post-H+6 irrigation risk",
              summary: "Late-day saturation prevents overnight dryback and increases root disease risk.",
              dependsOn: ["lit-window-h1-to-h6"],
              phases: ["Flower"],
            }),
          ],
          23,
        ),
      ],
    }),
    chapter({
      id: "ch-07-ec",
      number: 7,
      order: 7,
      titleFr: "L'EC comme outil de pilotage",
      titleEn: "EC as a steering tool",
      role: "learning_path",
      pageStart: 25,
      pageEnd: 28,
      purpose: "Teach EC meaning, in/out interpretation, phase targets, and steering role.",
      dependsOnChapterIds: ["ch-06-timing"],
      sections: [
        section(
          "ch-07-s1-ec-definition",
          1,
          "C'est quoi exactement, l'EC ?",
          "What EC is",
          "learning_path",
          "EC measures dissolved salts — in solution and in the root zone.",
          25,
          [
            n({
              kind: "concept",
              slug: "ec-definition",
              label: "EC definition",
              summary: "Electrical conductivity reflects total dissolved salts available to roots.",
              brainCategory: "Nutrition",
              relatedMetrics: ["ec_in", "ec_runoff"],
              phases: ["All"],
            }),
          ],
        ),
        section(
          "ch-07-s2-reading-ec",
          2,
          "Lire l'EC pour piloter",
          "Reading EC to steer",
          "learning_path",
          "Compare in vs out to infer uptake, accumulation, or starvation.",
          26,
          [
            n({
              kind: "concept",
              slug: "ec-in-out-interpretation",
              label: "EC in vs out interpretation",
              summary:
                "Out lower than in: uptake; equal: balance; higher: salt accumulation — adjust or flush gently.",
              dependsOn: ["ec-definition"],
              targetConceptSlug: "ec-runoff",
              brainCategory: "Irrigation",
              relatedMetrics: ["ec_in", "ec_runoff"],
              phases: ["Vegetative", "Flower"],
            }),
          ],
        ),
        section(
          "ch-07-s3-ec-by-phase",
          3,
          "Adapter l'EC à chaque phase",
          "EC by growth phase",
          "learning_path",
          "EC rises through clone → veg → stretch → generative → finish descent.",
          26,
          [
            n({
              kind: "rule",
              slug: "ec-phase-progression",
              label: "EC phase progression",
              summary:
                "Clone low (~0.5–0.8) → veg (~1.0–1.6) → stretch (~1.6–2.2) → generative up to ~2.8+ by genetics.",
              dependsOn: ["ec-in-out-interpretation"],
              relatedMetrics: ["ec_in"],
              brainCategory: "Nutrition",
              phases: ["Clone", "Vegetative", "Flower"],
            }),
          ],
        ),
        section(
          "ch-07-s4-ec-crop-steering",
          4,
          "Le rôle de l'EC dans le crop steering",
          "EC in crop steering",
          "learning_path",
          "EC concentration interacts with dryback to bias vegetative vs generative metabolism.",
          27,
          [
            n({
              kind: "concept",
              slug: "ec-crop-steering-role",
              label: "EC in crop steering",
              summary:
                "More irrigation dilutes root-zone EC (vegetative bias); dryback concentrates EC (generative bias).",
              dependsOn: ["ec-phase-progression", "dryback-definition"],
              brainCategory: "Crop Steering",
              relatedMetrics: ["ec_runoff", "dryback_percent"],
              phases: ["Vegetative", "Flower"],
            }),
          ],
        ),
        section(
          "ch-07-s5-ec-errors",
          5,
          "Les erreurs fréquentes à éviter",
          "Common EC mistakes",
          "learning_path",
          "Avoid blind EC chasing without reading plant and runoff signals.",
          27,
          [
            n({
              kind: "warning",
              slug: "ec-blind-escalation",
              label: "Blind EC escalation",
              summary: "Raising in EC without checking out trend risks lockout and tip burn.",
              dependsOn: ["ec-in-out-interpretation"],
              relatedMetrics: ["ec_runoff"],
              phases: ["Flower"],
            }),
          ],
          28,
        ),
      ],
    }),
    chapter({
      id: "ch-08-environment",
      number: 8,
      order: 8,
      titleFr: "Gestion de l'environnement : VPD, température, humidité",
      titleEn: "Environment: VPD, temperature, humidity",
      role: "learning_path",
      pageStart: 30,
      pageEnd: 37,
      purpose: "Link climate to transpiration, dryback speed, and steering outcomes.",
      dependsOnChapterIds: ["ch-07-ec"],
      sections: [
        section(
          "ch-08-s1-vpd-definition",
          1,
          "Le VPD, c'est quoi exactement ?",
          "What VPD is",
          "learning_path",
          "VPD drives transpiration and therefore dryback rate.",
          31,
          [
            n({
              kind: "concept",
              slug: "vpd-definition",
              label: "VPD definition",
              summary:
                "Vapor pressure deficit quantifies the drying force on leaves — the bridge between temp, RH, and transpiration.",
              targetConceptSlug: "vpd",
              brainCategory: "Environment",
              relatedMetrics: ["vpd", "temperature", "humidity"],
              phases: ["All"],
            }),
          ],
          30,
        ),
        section(
          "ch-08-s2-vpd-ranges",
          2,
          "Plages idéales de VPD par phase",
          "VPD ranges by phase",
          "learning_path",
          "Phase-specific VPD bands support clone, veg, generative, and late-flower goals.",
          32,
          [
            n({
              kind: "rule",
              slug: "vpd-ranges-by-phase",
              label: "VPD ranges by phase",
              summary:
                "Clone ~0.4–0.8 kPa; veg ~0.8–1.2; generative ~1.2–1.6; late flower up to ~1.8 for density.",
              dependsOn: ["vpd-definition"],
              relatedMetrics: ["vpd"],
              phases: ["Clone", "Vegetative", "Flower"],
            }),
          ],
        ),
        section(
          "ch-08-s3-temperature",
          3,
          "Température : moteur de la transpiration",
          "Temperature and transpiration",
          "learning_path",
          "Temperature shifts VPD and water demand independently of irrigation volume.",
          33,
          [
            n({
              kind: "concept",
              slug: "temperature-transpiration",
              label: "Temperature drives transpiration",
              summary: "Higher temps increase VPD and dryback speed — irrigation schedules must compensate.",
              dependsOn: ["vpd-definition"],
              targetConceptSlug: "temperature",
              brainCategory: "Environment",
              relatedMetrics: ["temperature", "vpd"],
              phases: ["All"],
            }),
          ],
        ),
        section(
          "ch-08-s4-humidity",
          4,
          "Humidité relative",
          "Relative humidity role",
          "learning_path",
          "RH is not comfort-only — it directly sets VPD and pathogen risk.",
          34,
          [
            n({
              kind: "concept",
              slug: "humidity-vpd-role",
              label: "Humidity and VPD",
              summary: "Adjust RH with temperature to hold target VPD bands for each growth phase.",
              dependsOn: ["vpd-ranges-by-phase"],
              targetConceptSlug: "humidity",
              brainCategory: "Environment",
              relatedMetrics: ["humidity", "vpd"],
              phases: ["All"],
            }),
          ],
        ),
        section(
          "ch-08-s5-environment-dryback",
          5,
          "Impact direct sur le dryback",
          "Environment impact on dryback",
          "learning_path",
          "High VPD accelerates overnight dryback — pulse plans must anticipate environmental swings.",
          35,
          [
            n({
              kind: "concept",
              slug: "environment-dryback-coupling",
              label: "Environment–dryback coupling",
              summary: "VPD and temperature change how fast P3 dryback completes before the next P1.",
              dependsOn: ["vpd-ranges-by-phase", "p3-overnight-dryback"],
              relatedMetrics: ["vpd", "dryback_percent"],
              phases: ["Vegetative", "Flower"],
            }),
          ],
        ),
        section(
          "ch-08-s6-climate-integration",
          6,
          "Intégration climatique dans le pilotage",
          "Climate integration in steering",
          "learning_path",
          "Treat irrigation and climate as one control loop, not isolated knobs.",
          36,
          [
            n({
              kind: "action",
              slug: "integrated-climate-irrigation",
              label: "Integrated climate–irrigation loop",
              summary:
                "When VPD spikes, revisit pulse count, volume, and timing together — not irrigation alone.",
              dependsOn: ["environment-dryback-coupling", "flower-vpd-light-synergy"],
              phases: ["All"],
            }),
          ],
          37,
        ),
      ],
    }),
    chapter({
      id: "ch-09-clone",
      number: 9,
      order: 9,
      titleFr: "Clonage et repiquage : l'irrigation des jeunes plants",
      titleEn: "Cloning and transplant irrigation",
      role: "learning_path",
      pageStart: 39,
      pageEnd: 44,
      purpose: "Protect fragile rooting phases before full pulse cycles begin.",
      dependsOnChapterIds: ["ch-08-environment"],
      sections: [
        section(
          "ch-09-s1-dome-phase",
          1,
          "Phase 1 : enracinement dans le dôme (jours 0 à 10)",
          "Phase 1: dome rooting (days 0–10)",
          "learning_path",
          "High humidity, minimal direct irrigation — roots not yet functional.",
          40,
          [
            n({
              kind: "concept",
              slug: "clone-dome-rooting",
              label: "Dome rooting phase",
              summary:
                "Clones depend on ambient humidity; over-watering causes stem rot, under-watering causes desiccation.",
              brainCategory: "Irrigation",
              relatedMetrics: ["humidity", "vpd"],
              phases: ["Clone"],
            }),
          ],
          39,
        ),
        section(
          "ch-09-s2-root-recovery",
          2,
          "Phase 2 : reprise racinaire (jours 10 à 14)",
          "Phase 2: root recovery (days 10–14)",
          "learning_path",
          "Gradual reduction of dome humidity as roots initiate.",
          41,
          [
            n({
              kind: "action",
              slug: "clone-humidity-wean",
              label: "Wean dome humidity",
              summary: "Lower humidity incrementally as roots appear — avoid abrupt VPD shock.",
              dependsOn: ["clone-dome-rooting", "vpd-ranges-by-phase"],
              phases: ["Clone"],
            }),
          ],
        ),
        section(
          "ch-09-s3-transplant",
          3,
          "Phase 3 : repiquage et acclimatation (jours 14 à 21)",
          "Phase 3: transplant acclimation (days 14–21)",
          "learning_path",
          "Surgical watering after transplant to drive outward root exploration.",
          42,
          [
            n({
              kind: "rule",
              slug: "transplant-gradient-watering",
              label: "Transplant gradient watering",
              summary:
                "Water around the cube only at repot — wet center, drier periphery — to force root colonization.",
              dependsOn: ["clone-humidity-wean"],
              phases: ["Clone", "Vegetative"],
            }),
            n({
              kind: "rule",
              slug: "transplant-ec-ph",
              label: "Transplant EC and pH",
              summary: "At repot use modest EC (~1.2 max) and pH ~5.9–6.2 with small volumes.",
              dependsOn: ["transplant-gradient-watering"],
              targetConceptSlug: "ph",
              brainCategory: "Nutrition",
              relatedMetrics: ["ec_in", "ph_in"],
              phases: ["Clone", "Vegetative"],
            }),
            n({
              kind: "action",
              slug: "transplant-light-ramp",
              label: "Progressive light ramp",
              summary: "Increase PPFD over 3–5 days after transplant — avoid jumping from clone to full intensity.",
              dependsOn: ["transplant-gradient-watering"],
              phases: ["Clone", "Vegetative"],
            }),
          ],
        ),
        section(
          "ch-09-s4-clone-signals",
          4,
          "Signes de bon départ vs stress",
          "Healthy start vs stress signals",
          "learning_path",
          "Visual diagnostics specific to young plants.",
          43,
          [
            n({
              kind: "warning",
              slug: "clone-wilt-low-rh",
              label: "Clone wilt from low RH",
              summary: "Soft wilting often means humidity too low; upward curl can mean VPD too high.",
              dependsOn: ["clone-dome-rooting"],
              phases: ["Clone"],
            }),
          ],
          44,
        ),
      ],
    }),
    chapter({
      id: "ch-10-finish",
      number: 10,
      order: 10,
      titleFr: "Finitions : phase finale, rinçage, et dernier arrosage",
      titleEn: "Finish: final phase, flush, and last irrigation",
      role: "learning_path",
      pageStart: 46,
      pageEnd: 53,
      purpose:
        "Botafarm progressive EC descent — not harsh plain-water cut — through final pulses and drydown.",
      dependsOnChapterIds: ["ch-09-clone"],
      sections: [
        section(
          "ch-10-s1-flush-objective",
          1,
          "Objectif du rinçage progressif",
          "Progressive flush objective",
          "learning_path",
          "Gradually lower root-zone EC while maintaining controlled hydration.",
          48,
          [
            n({
              kind: "concept",
              slug: "progressive-flush-objective",
              label: "Progressive flush objective",
              summary:
                "Finish phase reduces stored salts smoothly to support quality without shocking metabolism.",
              brainCategory: "Nutrition",
              relatedMetrics: ["ec_in", "ec_runoff"],
              phases: ["Flower", "Cure"],
            }),
          ],
          46,
        ),
        section(
          "ch-10-s2-ec-descent-start",
          2,
          "Quand démarrer la descente d'EC ?",
          "When to start EC descent",
          "learning_path",
          "Timing tied to trichome/resin goals and pre-harvest window.",
          49,
          [
            n({
              kind: "rule",
              slug: "finish-ec-descent-timing",
              label: "EC descent timing",
              summary: "Begin stepped EC reduction in the final ~2 weeks — not a single-day cut.",
              dependsOn: ["progressive-flush-objective"],
              phases: ["Flower"],
            }),
          ],
        ),
        section(
          "ch-10-s3-ec-descent-how",
          3,
          "Comment descendre l'EC progressivement ?",
          "How to step EC down",
          "learning_path",
          "Stepwise EC ladder with continued short pulses.",
          49,
          [
            n({
              kind: "action",
              slug: "finish-ec-step-ladder",
              label: "EC step ladder",
              summary:
                "Example: 2.8 → 2.0 → 1.4 → 1.0 → 0.7 → 0.5 mS/cm across final days with short pulses.",
              dependsOn: ["finish-ec-descent-timing"],
              relatedMetrics: ["ec_in"],
              phases: ["Flower"],
            }),
          ],
        ),
        section(
          "ch-10-s4-no-plain-water",
          4,
          "Pourquoi ne pas utiliser de l'eau claire ?",
          "Why not plain water",
          "learning_path",
          "Botafarm rejects abrupt zero-EC flush — maintains osmotic stability.",
          50,
          [
            n({
              kind: "rule",
              slug: "no-abrupt-plain-water-flush",
              label: "No abrupt plain-water flush",
              summary:
                "Sudden clear-water flush shocks roots; progressive dilution preserves function through harvest.",
              dependsOn: ["finish-ec-step-ladder"],
              phases: ["Flower"],
            }),
          ],
        ),
        section(
          "ch-10-s5-finish-stress",
          5,
          "Finition technique : stress final et arôme",
          "Final stress and aroma",
          "learning_path",
          "Controlled late stress supports terpene goals without collapse.",
          51,
          [
            n({
              kind: "concept",
              slug: "finish-aroma-stress",
              label: "Final aroma stress",
              summary: "Mild late stress paired with EC descent can support aroma — watch for over-drying.",
              dependsOn: ["no-abrupt-plain-water-flush"],
              phases: ["Flower"],
            }),
          ],
        ),
        section(
          "ch-10-s6-flush-indicators",
          6,
          "Indicateurs d'un bon rinçage progressif",
          "Progressive flush indicators",
          "learning_path",
          "Verify flush success via runoff EC trend and canopy signals.",
          52,
          [
            n({
              kind: "metric",
              slug: "finish-flush-indicators",
              label: "Flush success indicators",
              summary: "Out EC trends toward in; canopy stable; no sudden wilting during descent.",
              dependsOn: ["finish-aroma-stress"],
              relatedMetrics: ["ec_runoff", "ec_in"],
              phases: ["Flower"],
            }),
            n({
              kind: "rule",
              slug: "final-drydown-before-cut",
              label: "Final drydown before cut",
              summary: "End with 24–48h without irrigation before harvest after last low-EC pulses.",
              dependsOn: ["finish-flush-indicators"],
              phases: ["Flower", "Drying"],
            }),
          ],
          53,
        ),
      ],
    }),
    chapter({
      id: "ch-11-errors",
      number: 11,
      order: 11,
      titleFr: "Erreurs courantes et comment les corriger",
      titleEn: "Common errors and corrections",
      role: "learning_path",
      pageStart: 55,
      pageEnd: 57,
      purpose: "Diagnostic patterns for over- and under-irrigation with corrective actions.",
      dependsOnChapterIds: ["ch-10-finish"],
      sections: [
        section(
          "ch-11-s1-over-irrigation",
          1,
          "Sur-irrigation : le classique absolu",
          "Over-irrigation",
          "learning_path",
          "Recognize saturated substrate and rising out EC; correct with dryback and volume reduction.",
          56,
          [
            n({
              kind: "concept",
              slug: "over-irrigation-symptoms",
              label: "Over-irrigation symptoms",
              summary:
                "Droopy leaves with firm stems, glossy foliage, constantly wet cold substrate, climbing out EC.",
              brainCategory: "Irrigation",
              relatedMetrics: ["ec_runoff", "runoff_percent", "dryback_percent"],
              phases: ["Vegetative", "Flower"],
            }),
            n({
              kind: "action",
              slug: "over-irrigation-correction",
              label: "Over-irrigation correction",
              summary:
                "Reduce pulse volume and spacing; delay first pulse; increase morning dryback; lighten EC; verify root-zone aeration.",
              dependsOn: ["over-irrigation-symptoms"],
              phases: ["Vegetative", "Flower"],
            }),
          ],
        ),
        section(
          "ch-11-s2-under-irrigation",
          2,
          "Sous-irrigation : stress invisible mais ravageur",
          "Under-irrigation",
          "learning_path",
          "Recognize hydraulic stress and falling out EC; correct with measured increases.",
          57,
          [
            n({
              kind: "concept",
              slug: "under-irrigation-symptoms",
              label: "Under-irrigation symptoms",
              summary:
                "Wilting with soft stems, crisping leaves, dry deep substrate, out EC dropping below in.",
              brainCategory: "Irrigation",
              relatedMetrics: ["ec_runoff", "dryback_percent"],
              phases: ["Vegetative", "Flower"],
            }),
            n({
              kind: "action",
              slug: "under-irrigation-correction",
              label: "Under-irrigation correction",
              summary:
                "Increase pulse volume or count; verify real dryback; moderate VPD; temporarily reduce light if needed; raise in EC if starved.",
              dependsOn: ["under-irrigation-symptoms"],
              phases: ["Vegetative", "Flower"],
            }),
          ],
        ),
      ],
    }),
    chapter({
      id: "ch-12-reference-tables",
      number: 12,
      order: 12,
      titleFr: "Tableaux récapitulatifs",
      titleEn: "Reference tables and typical curves",
      role: "reference",
      pageStart: 58,
      pageEnd: 67,
      purpose: "Operational lookup — condenses EC, volume, timing, VPD, and diagnostics from prior chapters.",
      dependsOnChapterIds: [
        "ch-04-vegetative",
        "ch-05-flower",
        "ch-06-timing",
        "ch-07-ec",
        "ch-08-environment",
        "ch-10-finish",
      ],
      sections: [
        section(
          "ch-12-s1-ec-table",
          1,
          "Plages d'EC par phase",
          "EC ranges by phase",
          "reference",
          "Quick EC lookup: clone through progressive finish.",
          60,
          [
            n({
              kind: "metric",
              slug: "ref-ec-by-phase",
              label: "Reference EC by phase",
              summary:
                "Clone 0.5–0.8; veg 1.0–1.6; stretch 1.6–2.2; generative to ~2.8+; finish stepped down to ~0.5 final days.",
              relatedMetrics: ["ec_in", "ec_runoff"],
              brainCategory: "Nutrition",
              phases: ["Clone", "Vegetative", "Flower"],
            }),
          ],
        ),
        section(
          "ch-12-s2-volume-frequency",
          2,
          "Volume, fréquence, dryback",
          "Volume, frequency, dryback",
          "reference",
          "Pulse volume and count reference by phase.",
          61,
          [
            n({
              kind: "metric",
              slug: "ref-volume-frequency-dryback",
              label: "Reference volume & frequency",
              summary:
                "Veg: 1–2×/day at 5–8% per pulse, 5–10% dryback; flower: 4–8×/day at 1.5–3% per pulse, 15–30%+ dryback, 10–20% runoff.",
              relatedMetrics: [
                "irrigation_count",
                "irrigation_volume_per_event",
                "dryback_percent",
                "runoff_percent",
              ],
              phases: ["Vegetative", "Flower"],
            }),
          ],
        ),
        section(
          "ch-12-s3-timing-table",
          3,
          "Timing stratégique",
          "Strategic timing",
          "reference",
          "H+1 to H+6 lit-window rules.",
          62,
          [
            n({
              kind: "rule",
              slug: "ref-timing-h-window",
              label: "Reference timing window",
              summary: "Never at lights-on; irrigate H+1 through H+6 only; no night irrigation.",
              relatedMetrics: ["irrigation_count"],
              phases: ["Vegetative", "Flower"],
            }),
          ],
        ),
        section(
          "ch-12-s4-vpd-table",
          4,
          "VPD par phase",
          "VPD by phase",
          "reference",
          "Target VPD bands for clone through late flower.",
          63,
          [
            n({
              kind: "metric",
              slug: "ref-vpd-by-phase",
              label: "Reference VPD by phase",
              summary: "Clone 0.4–0.8; veg 0.8–1.2; generative 1.2–1.6; late flower up to ~1.8 kPa.",
              relatedMetrics: ["vpd"],
              phases: ["Clone", "Vegetative", "Flower"],
            }),
          ],
        ),
        section(
          "ch-12-s5-ec-in-out-table",
          5,
          "Lecture croisée EC in/out",
          "EC in/out cross-read",
          "reference",
          "Decision table for out vs in EC.",
          64,
          [
            n({
              kind: "rule",
              slug: "ref-ec-out-interpretation",
              label: "Reference EC out interpretation",
              summary: "Out < in: uptake; out = in: balance; out > in: accumulation — gentle half-EC flush day then resume.",
              relatedMetrics: ["ec_in", "ec_runoff"],
              phases: ["Vegetative", "Flower"],
            }),
          ],
        ),
        section(
          "ch-12-s6-finish-table",
          6,
          "Phase finale EC progressive",
          "Progressive finish EC",
          "reference",
          "Botafarm stepped finish schedule — not plain water.",
          65,
          [
            n({
              kind: "metric",
              slug: "ref-finish-ec-ladder",
              label: "Reference finish EC ladder",
              summary:
                "Example J-14 @ 2.8 stepping down to ~0.5 at J-1 with short pulses; 24–48h drydown before cut.",
              relatedMetrics: ["ec_in"],
              phases: ["Flower"],
            }),
          ],
        ),
        section(
          "ch-12-s7-visual-diagnostics",
          7,
          "Repères visuels rapides",
          "Quick visual diagnostics",
          "reference",
          "Symptom → likely cause lookup.",
          66,
          [
            n({
              kind: "warning",
              slug: "ref-visual-diagnostics",
              label: "Reference visual diagnostics",
              summary:
                "Firm stem wilt = over-water; soft wilt = under-water; tip burn = high EC; stretch = low EC/VPD; mold = high RH + late water.",
              phases: ["Vegetative", "Flower"],
            }),
          ],
        ),
        section(
          "ch-12-s8-checklist",
          8,
          "Checklist opérationnelle",
          "Operational checklist",
          "reference",
          "Printable session checklist — theory to operations.",
          67,
          [
            n({
              kind: "action",
              slug: "ref-session-checklist",
              label: "Session checklist",
              summary:
                "Use tables before each session to verify EC, pulse plan, VPD, dryback target, and diagnostic signs.",
              dependsOn: ["ref-ec-by-phase", "ref-volume-frequency-dryback"],
              phases: ["All"],
            }),
          ],
        ),
      ],
    }),
    chapter({
      id: "ch-13-conclusion",
      number: 13,
      order: 13,
      titleFr: "Conclusion : irriguer, c'est cultiver avec intelligence",
      titleEn: "Conclusion: irrigate with intelligence",
      role: "learning_path",
      pageStart: 76,
      pageEnd: 78,
      purpose: "Synthesize irrigation as orchestration — reading plants, substrate, and climate together.",
      dependsOnChapterIds: ["ch-12-reference-tables"],
      sections: [
        section(
          "ch-13-s1-synthesis",
          1,
          "Synthèse du pilotage",
          "Steering synthesis",
          "learning_path",
          "Close the learning path — from foundations to daily orchestration.",
          76,
          [
            n({
              kind: "concept",
              slug: "irrigation-as-orchestration",
              label: "Irrigation as orchestration",
              summary:
                "Expert cultivation reads substrate and climate, adjusts parameters deliberately, and treats each pulse as intent.",
              dependsOn: ["ref-session-checklist"],
              targetConceptSlug: "irrigation-strategy",
              brainCategory: "Irrigation",
              phases: ["All"],
            }),
            n({
              kind: "concept",
              slug: "continuous-adjustment-mindset",
              label: "Continuous adjustment mindset",
              summary: "No fixed recipe — observe response, measure dryback and EC, refine the next photoperiod.",
              dependsOn: ["irrigation-as-orchestration"],
              phases: ["All"],
            }),
          ],
          78,
        ),
      ],
    }),
    chapter({
      id: "ch-bonus-precision",
      number: 0,
      order: 14,
      titleFr: "BONUS — Stratégie d'irrigation de précision",
      titleEn: "BONUS — Precision irrigation strategy",
      role: "reference",
      pageStart: 79,
      pageEnd: 113,
      purpose:
        "Deep-dive reference: VWC/EC 24h cycles, P0–P3 phases, and veg vs generative pilotage scenarios.",
      dependsOnChapterIds: ["ch-06-timing", "ch-12-reference-tables"],
      sections: [
        section(
          "ch-bonus-s1-why-precision",
          1,
          "Pourquoi l'irrigation de précision",
          "Why precision irrigation",
          "reference",
          "Motivation and tools overview for VWC-based steering.",
          79,
          [
            n({
              kind: "concept",
              slug: "bonus-precision-framing",
              label: "Precision irrigation framing",
              summary:
                "Precision irrigation balances training inputs (light, CO₂, climate) with timed water and nutrition delivery.",
              phases: ["All"],
            }),
          ],
        ),
        section(
          "ch-bonus-s2-p0-p3-veg",
          2,
          "Cycle 24h végétatif — P0 à P3",
          "Vegetative 24h cycle P0–P3",
          "reference",
          "VWC + EC cyclic diagram for vegetative steering.",
          85,
          [
            n({
              kind: "concept",
              slug: "bonus-p0-wake",
              label: "P0 wake — no immediate irrigation",
              summary:
                "At lights-on, allow continued dryback so stomata and transpiration activate before first pulse.",
              dependsOn: ["p1-first-shots"],
              targetConceptSlug: "p1-irrigation",
              phases: ["Vegetative"],
            }),
            n({
              kind: "concept",
              slug: "bonus-p1-ramp-veg",
              label: "P1 ramp (vegetative)",
              summary:
                "P1: spaced small pulses (2–6% pot volume) every 15–30 min until field capacity; target 2–7% runoff.",
              dependsOn: ["bonus-p0-wake"],
              phases: ["Vegetative"],
            }),
            n({
              kind: "concept",
              slug: "bonus-p2-maintenance-veg",
              label: "P2 maintenance (vegetative)",
              summary: "P2 activates if dryback exceeds ~25% during the day — stabilizes VWC in target band.",
              dependsOn: ["bonus-p1-ramp-veg"],
              targetConceptSlug: "p2-irrigation",
              phases: ["Vegetative"],
            }),
            n({
              kind: "concept",
              slug: "bonus-p3-night-veg",
              label: "P3 overnight (vegetative)",
              summary: "Lights-off: zero irrigation until next P0/P1 — dryback for root respiration.",
              dependsOn: ["bonus-p2-maintenance-veg"],
              targetConceptSlug: "p3-irrigation",
              phases: ["Vegetative"],
            }),
          ],
          88,
        ),
        section(
          "ch-bonus-s3-p1-deep-dive",
          3,
          "Approfondissement P1",
          "P1 deep dive",
          "reference",
          "Execution detail for rehydration after dryback.",
          88,
          [
            n({
              kind: "action",
              slug: "bonus-p1-execution",
              label: "P1 execution detail",
              summary:
                "Rehydrate progressively after dryback — shot uniformity and homogeneity determine daily stability.",
              dependsOn: ["bonus-p1-ramp-veg"],
              phases: ["Vegetative", "Flower"],
            }),
          ],
        ),
        section(
          "ch-bonus-s4-veg-vs-gen",
          4,
          "Pilotage végétatif vs génératif",
          "Vegetative vs generative pilotage",
          "reference",
          "When to add or remove P2 shots to bias steering direction.",
          95,
          [
            n({
              kind: "rule",
              slug: "bonus-veg-more-p2",
              label: "Vegetative: add P2",
              summary: "More P2 maintenance = less stress = higher VWC = vegetative bias.",
              dependsOn: ["bonus-p2-maintenance-veg"],
              targetConceptSlug: "vegetative-steering",
              brainCategory: "Crop Steering",
              phases: ["Vegetative"],
            }),
            n({
              kind: "rule",
              slug: "bonus-gen-less-p2",
              label: "Generative: reduce P2",
              summary: "Fewer or no P2 shots = faster drydown = stronger generative hydraulic stress.",
              dependsOn: ["bonus-p2-maintenance-veg"],
              targetConceptSlug: "generative-steering",
              brainCategory: "Crop Steering",
              phases: ["Flower"],
            }),
          ],
        ),
        section(
          "ch-bonus-s5-scenario-18-6",
          5,
          "Scénario 18/6 végétatif",
          "18/6 vegetative scenario",
          "reference",
          "Single daily irrigation pattern under 18/6 with 30–40% 24h dryback target.",
          106,
          [
            n({
              kind: "metric",
              slug: "bonus-scenario-18-6",
              label: "18/6 vegetative scenario",
              summary:
                "One irrigation after lights-on; substrate dries through lit period and night; ~30–40% 24h dryback target.",
              relatedMetrics: ["dryback_percent", "irrigation_count"],
              phases: ["Vegetative"],
            }),
          ],
        ),
        section(
          "ch-bonus-s6-scenario-12-12-stretch",
          6,
          "Scénario 12/12 stretch / rinçage",
          "12/12 stretch / flush scenario",
          "reference",
          "Higher dryback generative signal early 12/12 or progressive flush.",
          106,
          [
            n({
              kind: "metric",
              slug: "bonus-scenario-12-12-stretch",
              label: "12/12 stretch scenario",
              summary:
                "Single daily pulse at photoperiod start; faster daytime drying; ~35–50% dryback for generative signaling.",
              relatedMetrics: ["dryback_percent"],
              phases: ["Flower", "Pre-Flower"],
            }),
          ],
        ),
        section(
          "ch-bonus-s7-scenario-bulking",
          7,
          "Scénario 12/12 bulking",
          "12/12 bulking scenario",
          "reference",
          "Late-flower bulking with moderated dryback stress.",
          106,
          [
            n({
              kind: "metric",
              slug: "bonus-scenario-bulking",
              label: "Bulking scenario",
              summary:
                "Similar single-pulse pattern with ~30–40% dryback — slightly less aggressive stress for flower swell.",
              relatedMetrics: ["dryback_percent"],
              phases: ["Flower"],
            }),
          ],
        ),
      ],
    }),
  ],
});

const withDependencies = rewireDependsOnToIrrIds(RAW_IRRIGATION_HANDBOOK_MAP);

assertValidBookMap(withDependencies);

export const IRRIGATION_HANDBOOK_BOOK_MAP: BookMap = withDependencies;
